---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Add node
      bigip_node:
        server: "{{ inventory_hostname }}"
        validate_certs: no
        state: "present"
        partition: "Common"
        host: "{{ host_ip }}"
        name: "{{ member_name }}"
        monitors:
          - /Common/icmp
      when: input_state == 'add'

    - name: Add node
      bigip_node:
        server: "{{ inventory_hostname }}"
        validate_certs: no
        state: "absent"
        partition: "Common"
        host: "{{ host_ip }}"
        name: "{{ member_name }}"
        monitors:
          - /Common/icmp
      when: input_state == 'remove'