- hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Collect all BIG-IP facts
      bigip_device_facts:
        gather_subset:
          - all
        provider:
          server: "{{ inventory_hostname }}"
          user: "{{ username }}"
          password: "{{ password }}"
          transport: rest
          validate_certs: yes
      delegate_to: localhost

