---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Create a pool
      bigip_pool:
        lb_method: "ratio_member"
        name: "Ansible_test01"
        user: "admin"
        password: "admin"
        server: 192.168.1.100
        slow_ramp_time: 120
        validate_certs: "no"

    - name: Create node1
      bigip_node:
        host: "100.100.100.100"
        name: "Ansible-node-1"
        user: "admin"
        password: "admin"
        server: 192.168.1.100
        validate_certs: "no"

    - name: Create node2
      bigip_node:
        host: "100.100.100.200"
        name: "Ansible-node-2"
        user: "admin"
        password: "admin"
        server: 192.168.1.100
        validate_certs: "no"

    - name: Add nodes to pool
      bigip_pool_member:
        description: "Ansible-webserver-1"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        user: "admin"
        password: "admin"
        pool: "Ansible-web"
        port: "80"
        server: 192.168.1.100
        validate_certs: "no"
      with_items:
        - { host: "100.100.100.100", name: "Ansible-node-1" }
        - { host: "100.100.100.200", name: "Ansible-node-2" }
