---
- name: Collect BIG-IP facts
  bigip_facts:
    server: "{{ inventory_hostname }}"
    include: "pool"
    filter: "{{ pool_name }}"

- set_fact:
    pool_path: /Common/{{ pool_name }}

- name: Disable node pool member
  bigip_node:
    server: "{{ inventory_hostname }}"
    state: "present"
    session_state: "disabled"
    monitor_state: "disabled"
    partition: "Common"
    name: "{{ inventory_hostname }}"
  when: pool['{{ pool_path }}'].active_member_count >= 2

- name: Patch the system
  yum:
    name: yum
    state: latest
  delegate_to: "{{ inventory_hostname }}"

- name: Enable node pool member
  bigip_node:
      server: "{{ inventory_hostname }}"
      state: "present"
      session_state: "enabled"
      monitor_state: "enabled"
      partition: "Common"
      name: "{{ inventory_hostname }}"

- name: Disable node pool member
  bigip_node:
    server: "{{ inventory_hostname }}"
    state: "present"
    session_state: "disabled"
    monitor_state: "disabled"
    partition: "Common"
    host: "{{ host_ip2}}"
    name: "{{ member_name2 }}"
  when: pool['{{ pool_path }}'].active_member_count >= 2

- name: Patch the system
  yum:
    name: yum
    state: latest
  delegate_to: "{{ host_ip2 }}"

- name: Enable node pool member
  bigip_node:
      server: "{{ inventory_hostname }}"
      state: "present"
      session_state: "enabled"
      monitor_state: "enabled"
      partition: "Common"
      host: "{{ host_ip2 }}"
      name: "{{ member_name2 }}"