---
- name: Collect BIG-IP facts
  bigip_facts:
    server: "192.168.1.100"
    user: "admin"
    password: "admin"
    include: "pool"
    filter: "{{ pool_name }}"

- set_fact:
    pool_path: /Common/{{ pool_name }}

- name: Disable node pool member
  bigip_node:
    server: "{{ server }}"
    state: "present"
    user: "{{ user }}"
    password: "{{ password }}"
    session_state: "disabled"
    monitor_state: "disabled"
    partition: "Common"
    host: "{{ host_ip1}}"
    name: "{{ member_name1 }}"
  when: pool['{{ pool_path }}'].active_member_count >= 2

- name: Patch the system
  yum:
    host: "{{ host_ip1 }}"
    name: yum
    state: latest

- name: Enable node pool member
  bigip_node:
      server: "{{ server }}"
      state: "present"
      user: "{{ user }}"
      password: "{{ password }}"
      session_state: "enabled"
      monitor_state: "enabled"
      partition: "Common"
      host: "{{ host_ip1 }}"
      name: "{{ member_name1 }}"

- name: Disable node pool member
  bigip_node:
    server: "{{ server }}"
    state: "present"
    user: "{{ user }}"
    password: "{{ password }}"
    session_state: "disabled"
    monitor_state: "disabled"
    partition: "Common"
    host: "{{ host_ip2}}"
    name: "{{ member_name2 }}"
  when: pool['{{ pool_path }}'].active_member_count >= 2

- name: Patch the system
  yum:
    host: "{{ host_ip2 }}"
    name: yum
    state: latest

- name: Enable node pool member
  bigip_node:
      server: "{{ server }}"
      state: "present"
      user: "{{ user }}"
      password: "{{ password }}"
      session_state: "enabled"
      monitor_state: "enabled"
      partition: "Common"
      host: "{{ host_ip2 }}"
      name: "{{ member_name2 }}"