---
- name: Add virtual server
  bigip_virtual_server:
      server: "{{ server }}"
      user: "{{ user }}"
      password: "{{ password }}"
      state: present
      partition: MyPartition
      name: "{{ virtual_server_name }}"
      destination: "{{ vip_address}}"
      port: 443
      pool: "{{ pool_name }}"
      snat: Automap