---
- name: Add virtual server
  bigip_virtual_server:
      server: "{{ inventory_hostname }}"
      state: present
      name: "{{ virtual_server_name }}"
      destination: "{{ vip_address }}"
      port: 443
      pool: "{{ pool_name }}"
      snat: Automap
      validate_certs: "no"
