---
- name: Disable node pool member
  bigip_node:
      server: "{{ server }}"
      state: "present"
      user: "{{ user }}"
      password: "{{ password }}"
      session_state: "disabled"
      monitor_state: "disabled"
      partition: "Common"
      host: "{{ host_ip}}"
      name: "{{ member_name }}"
