---
- name: Add node
  bigip_node:
      server: "{{ server }}"
      user: "{{ username }}"
      password: "{{ password }}"
      state: "present"
      partition: "Common"
      host: "{{ host_ip }}"
      name: "{{ member_name }}"
      monitors:
        - /Common/icmp